### ISSUE TITLE
Print latest commit number into log file

### ISSUE THREAD

**Issue by nippoo** [klusta-team/klustakwik#23]
Currently there's no way of knowing which version of the program was used.

**Comment by thesamovar** [comment]
I just checked your code for this (the print_version branch) and it works on Windows in the case where git is not present. I didn't check for the case when git exists because I don't have a command line version of git on my Windows machine! On the other hand, it won't work when building with MSVC because it doesn't use the makefile so VERSION is not defined. We should have the fallback defined in the C++ code rather than in the makefile, e.g.

```
#ifndef VERSION
#define VERSION 0.3.0
#endif
```

This fallback should only be in one place.

Maybe there is also a solution for MSVC to get the git information, but I don't know what it is.

**Comment by thesamovar** [comment]
I wonder if we could include the ``git describe`` code in KlustaKwik itself? i.e. it tries running that command and copying the output and if it fails falls back? That way it would work for both MSVC and gcc.

**Comment by nippoo** [comment]
Yes to the ifndef. But shouldn't include the ```git describe``` code in KK.

1) if the user compiles the binary then moves it somewhere else (like /usr/local/bin) the git command will fail
2) more worryingly, if the user pulls a later version of KK or switches to a branch (but doesn't recompile) the code will report the wrong version (the binary will still be old, but will think it's newer).

**Comment by thesamovar** [comment]
Good points. OK, so too bad for MSVC I guess.

**Comment by nippoo** [comment]
Actually, hm. Where will be the ```ifndef``` be? ```VERSION``` will always be defined if using the makefile.  Or maybe I can put it in some conditional block...

**Comment by thesamovar** [comment]
It only needs to be in the file where VERSION is used.

**Comment by nippoo** [comment]
Yes, but what I mean is that:

``` CFLAGS = -Wall -c -Wno-write-strings $(OPTIMISATIONS) -DVERSION=\"$(GIT_VERSION)\"```

means that ```VERSION``` is always defined even if the git command fails (it's just ```""```). ... unless I'm wrong

**Comment by thesamovar** [comment]
That's OK: you won't use that makefile if you're on MSVC.
